[development]  
DEBUG = true  
BD_NAME = "development"
DATABASE_URL = "mysql+pymysql://root@localhost:3306/development" 
connection_string = "mysql+pymysql://root@localhost:3306/development"
DATABASE_MEMORY = false
FLASK_APP="api.src"
path_modelo_solicitacao_xml = "template_xml/solicitacao.xml"
DB_HOST= ""
BD_PORT= ""
BD_PASSWORD= ""
BD_USER= ""
pythonpath="api"
path_image_schema_bd = "api/src/schema"
BASE_URL = "http://127.0.0.1:5000"
API_SOAP_AUTORIZACAO_EXECUCAO_SP_SADT = "http://fakeapi.com.br"
JWT_SECRET_KEY="8*2@jwje#djdjd*11222*11"

[testing]  
DEBUG = true  
BD_NAME = "testing.db"
connection_string = "sqlite:///C:\\xampp\\htdocs\\envie_me_o_token\\api\\src\\instance\\testing.db"
DATABASE_MEMORY = true
FLASK_APP="api.src"
path_modelo_solicitacao_xml = "template_xml/solicitacao.xml"
DB_HOST= ""
BD_PORT= ""
BD_PASSWORD= ""
BD_USER= ""
pythonpath="api"
path_image_schema_bd = "api/src/schema"
BASE_URL = "http://127.0.0.1:5000"
API_SOAP_AUTORIZACAO_EXECUCAO_SP_SADT = "http://fakeapi.com.br" 
DATABASE_URL = "sqlite:///C:\\xampp\\htdocs\\envie_me_o_token\\api\\src\\instance\\testing.db"
JWT_SECRET_KEY="8*2@jwje#djdjd*11222*11"

[staging]  
DEBUG = true  
BD_NAME = "staging"
connection_string = "mysql+pymysql://root@localhost:3306/staging"
DATABASE_MEMORY= false
FLASK_APP="api.src"
path_modelo_solicitacao_xml = "template_xml/solicitacao.xml"
DB_HOST= ""
BD_PORT= ""
BD_PASSWORD= ""
BD_USER= ""
pythonpath="api"
path_image_schema_bd = "api/src/schema"
BASE_URL = "http://127.0.0.1:5000"
API_SOAP_AUTORIZACAO_EXECUCAO_SP_SADT = "http://fakeapi.com.br" 
DATABASE_URL = "mysql+pymysql://root@localhost:3306/staging"
JWT_SECRET_KEY="8*2@jwje#djdjd*11222*11"

[production]  
DEBUG = false
BD_NAME = "production"
connection_string = "mysql+pymysql://root@localhost:3306/production"
DATABASE_MEMORY= "false"
FLASK_APP="api.src"
path_modelo_solicitacao_xml = "template_xml/solicitacao.xml"
DB_HOST= ""
BD_PORT= ""
BD_PASSWORD= ""
BD_USER= ""
pythonpath="api"
path_image_schema_bd = "api/src/schema"
BASE_URL = "http://127.0.0.1:5000"
API_SOAP_AUTORIZACAO_EXECUCAO_SP_SADT = "http://fakeapi.com.br" 
DATABASE_URL = "mysql+pymysql://root@localhost:3306/production"
USE_CLASS_FAKE = false
JWT_SECRET_KEY="8*2@jwje#djdjd*11222*11"